name: Build and Sign Release
on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # allows the action to create a release
      id-token: write # needed for cosign to work

    name: build-and-release
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5.2.0
        with:
          go-version: stable

      - name: Build
        run: go build -buildvcs=true ./cmd/confidential-witness

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign the binary with GitHub OIDC Token
        run: cosign sign-blob --yes confidential-witness --bundle cosign.bundle

      - name: Release
        run: gh release create ${{ github.ref_name }} --generate-notes confidential-witness cosign.bundle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
